/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPathExpressionException;
import net.sf.saxon.s9api.SaxonApiException;
import net.sf.saxon.s9api.XdmValue;
import org.jdom2.Document;
import org.xml.sax.SAXException;

/**
 *
 * @author isabe
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        addJogador = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        addJogButton = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        remJogador = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        remJogButton = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        newIdade = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        nIdadeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        newNacionalidade = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        nNacionalidadeButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        newClube = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        nClubeButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        newEstado = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        nEstadoButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        XPATH_nome = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        XPATH_clube = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        XPATH_nacionalidade = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        XPATH_posicao = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        XPATH_intervaloIdade = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        XPATH_selecao = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        geral = new javax.swing.JMenu();
        VerXML = new javax.swing.JMenuItem();
        validarDTD = new javax.swing.JMenuItem();
        validarXSD = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        alterarDados = new javax.swing.JMenu();
        adicionarJog = new javax.swing.JMenuItem();
        eliminarJog = new javax.swing.JMenuItem();
        mudarIdade = new javax.swing.JMenuItem();
        mudarNacion = new javax.swing.JMenuItem();
        mudarClube = new javax.swing.JMenuItem();
        mudarEstado = new javax.swing.JMenuItem();
        efetuarPesquisas = new javax.swing.JMenu();
        pesquisarNome = new javax.swing.JMenuItem();
        pesquisarClube = new javax.swing.JMenuItem();
        pesquisarNacion = new javax.swing.JMenuItem();
        pesquisarPos = new javax.swing.JMenuItem();
        pesquisarSituacao = new javax.swing.JMenuItem();
        pesquisarIntervaloIdade = new javax.swing.JMenuItem();
        pesquisarSelecao = new javax.swing.JMenuItem();
        gerarOutputs = new javax.swing.JMenu();
        HMTL_fotos = new javax.swing.JMenuItem();
        XML_clube = new javax.swing.JMenuItem();
        TXT_nacionalidade = new javax.swing.JMenuItem();
        XML_top = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setText("Nome do jogador a adicionar");

        addJogButton.setText("OK");
        addJogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJogButtonActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addJogadorLayout = new javax.swing.GroupLayout(addJogador.getContentPane());
        addJogador.getContentPane().setLayout(addJogadorLayout);
        addJogadorLayout.setHorizontalGroup(
            addJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addJogadorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(96, 96, 96))
            .addGroup(addJogadorLayout.createSequentialGroup()
                .addGroup(addJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJogadorLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(addJogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addJogadorLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        addJogadorLayout.setVerticalGroup(
            addJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJogadorLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(addJogButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setText("Nome do jogador a remover");

        remJogButton.setText("OK");
        remJogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remJogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout remJogadorLayout = new javax.swing.GroupLayout(remJogador.getContentPane());
        remJogador.getContentPane().setLayout(remJogadorLayout);
        remJogadorLayout.setHorizontalGroup(
            remJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, remJogadorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(96, 96, 96))
            .addGroup(remJogadorLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(remJogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, remJogadorLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        remJogadorLayout.setVerticalGroup(
            remJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remJogadorLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(remJogButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel4.setText("Nome do jogador ");

        nIdadeButton.setText("OK");
        nIdadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nIdadeButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel5.setText("Nova idade");

        javax.swing.GroupLayout newIdadeLayout = new javax.swing.GroupLayout(newIdade.getContentPane());
        newIdade.getContentPane().setLayout(newIdadeLayout);
        newIdadeLayout.setHorizontalGroup(
            newIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newIdadeLayout.createSequentialGroup()
                .addGroup(newIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newIdadeLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(nIdadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newIdadeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(newIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        newIdadeLayout.setVerticalGroup(
            newIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newIdadeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(newIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(nIdadeButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel6.setText("Nome do jogador ");

        nNacionalidadeButton.setText("OK");
        nNacionalidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nNacionalidadeButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel7.setText("Nova nacionalidade");

        javax.swing.GroupLayout newNacionalidadeLayout = new javax.swing.GroupLayout(newNacionalidade.getContentPane());
        newNacionalidade.getContentPane().setLayout(newNacionalidadeLayout);
        newNacionalidadeLayout.setHorizontalGroup(
            newNacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newNacionalidadeLayout.createSequentialGroup()
                .addGroup(newNacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newNacionalidadeLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(nNacionalidadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newNacionalidadeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newNacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(newNacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        newNacionalidadeLayout.setVerticalGroup(
            newNacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newNacionalidadeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(newNacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newNacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(nNacionalidadeButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel8.setText("Nome do jogador ");

        nClubeButton.setText("OK");
        nClubeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nClubeButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel9.setText("Novo clube");

        javax.swing.GroupLayout newClubeLayout = new javax.swing.GroupLayout(newClube.getContentPane());
        newClube.getContentPane().setLayout(newClubeLayout);
        newClubeLayout.setHorizontalGroup(
            newClubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClubeLayout.createSequentialGroup()
                .addGroup(newClubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newClubeLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(nClubeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newClubeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newClubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(newClubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(jTextField4))))
                .addGap(45, 45, 45))
        );
        newClubeLayout.setVerticalGroup(
            newClubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClubeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(newClubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(newClubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addComponent(nClubeButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel10.setText("Nome do jogador ");

        nEstadoButton.setText("OK");
        nEstadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nEstadoButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel11.setText("Novo estado");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newEstadoLayout = new javax.swing.GroupLayout(newEstado.getContentPane());
        newEstado.getContentPane().setLayout(newEstadoLayout);
        newEstadoLayout.setHorizontalGroup(
            newEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEstadoLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(nEstadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(newEstadoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25)
                .addGroup(newEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jTextField6))
                .addGap(104, 104, 104))
        );
        newEstadoLayout.setVerticalGroup(
            newEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEstadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(newEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(nEstadoButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel12.setText("Palavra de pesquisa:");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout XPATH_nomeLayout = new javax.swing.GroupLayout(XPATH_nome.getContentPane());
        XPATH_nome.getContentPane().setLayout(XPATH_nomeLayout);
        XPATH_nomeLayout.setHorizontalGroup(
            XPATH_nomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_nomeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(XPATH_nomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(XPATH_nomeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        XPATH_nomeLayout.setVerticalGroup(
            XPATH_nomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_nomeLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(XPATH_nomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        jLabel13.setText("Palavra de pesquisa:");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout XPATH_clubeLayout = new javax.swing.GroupLayout(XPATH_clube.getContentPane());
        XPATH_clube.getContentPane().setLayout(XPATH_clubeLayout);
        XPATH_clubeLayout.setHorizontalGroup(
            XPATH_clubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_clubeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(XPATH_clubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(XPATH_clubeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        XPATH_clubeLayout.setVerticalGroup(
            XPATH_clubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_clubeLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(XPATH_clubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(32, 32, 32))
        );

        jLabel14.setText("Palavra de pesquisa:");

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout XPATH_nacionalidadeLayout = new javax.swing.GroupLayout(XPATH_nacionalidade.getContentPane());
        XPATH_nacionalidade.getContentPane().setLayout(XPATH_nacionalidadeLayout);
        XPATH_nacionalidadeLayout.setHorizontalGroup(
            XPATH_nacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_nacionalidadeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(XPATH_nacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(XPATH_nacionalidadeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton3)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        XPATH_nacionalidadeLayout.setVerticalGroup(
            XPATH_nacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_nacionalidadeLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(XPATH_nacionalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(32, 32, 32))
        );

        jLabel15.setText("Palavra de pesquisa:");

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout XPATH_posicaoLayout = new javax.swing.GroupLayout(XPATH_posicao.getContentPane());
        XPATH_posicao.getContentPane().setLayout(XPATH_posicaoLayout);
        XPATH_posicaoLayout.setHorizontalGroup(
            XPATH_posicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_posicaoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(XPATH_posicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(XPATH_posicaoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        XPATH_posicaoLayout.setVerticalGroup(
            XPATH_posicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_posicaoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(XPATH_posicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(32, 32, 32))
        );

        jLabel18.setText("Idade minima");

        jLabel19.setText("Idade máxima");

        jButton7.setText("OK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout XPATH_intervaloIdadeLayout = new javax.swing.GroupLayout(XPATH_intervaloIdade.getContentPane());
        XPATH_intervaloIdade.getContentPane().setLayout(XPATH_intervaloIdadeLayout);
        XPATH_intervaloIdadeLayout.setHorizontalGroup(
            XPATH_intervaloIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_intervaloIdadeLayout.createSequentialGroup()
                .addGroup(XPATH_intervaloIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(XPATH_intervaloIdadeLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(XPATH_intervaloIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(41, 41, 41)
                        .addGroup(XPATH_intervaloIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField17, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextField18)))
                    .addGroup(XPATH_intervaloIdadeLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton7)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        XPATH_intervaloIdadeLayout.setVerticalGroup(
            XPATH_intervaloIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_intervaloIdadeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(XPATH_intervaloIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(XPATH_intervaloIdadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel17.setText("Palavra de pesquisa:");

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout XPATH_selecaoLayout = new javax.swing.GroupLayout(XPATH_selecao.getContentPane());
        XPATH_selecao.getContentPane().setLayout(XPATH_selecaoLayout);
        XPATH_selecaoLayout.setHorizontalGroup(
            XPATH_selecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_selecaoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(XPATH_selecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(XPATH_selecaoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton6)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        XPATH_selecaoLayout.setVerticalGroup(
            XPATH_selecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XPATH_selecaoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(XPATH_selecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setName("Informacao"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 37)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(121, 173, 225));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informação sobre jogadores de futebol");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        jTree1.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Jogador");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("nome");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("nome completo do jogador");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("fotografia (link)");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("data de nascimento");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("idade");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("nacionalidade");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("altura");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("peso");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("pé preferencial");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("posições onde joga");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("clube atual");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("clubes anteriores");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("seleção nacional");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("prémios ganhos");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("estado atual: ativo, reformado");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("valor do contrato");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("empresário");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ranking");
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
                .addContainerGap())
        );

        geral.setText("Opções Gerais");
        geral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geralActionPerformed(evt);
            }
        });

        VerXML.setText("Ver conteúdo do ficheiro");
        VerXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerXMLActionPerformed(evt);
            }
        });
        geral.add(VerXML);

        validarDTD.setText("Validar modelo de dados- DTD");
        validarDTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarDTDActionPerformed(evt);
            }
        });
        geral.add(validarDTD);

        validarXSD.setText("Validar modelo de dados- XSD");
        validarXSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarXSDActionPerformed(evt);
            }
        });
        geral.add(validarXSD);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        geral.add(Sair);

        jMenuBar1.add(geral);

        alterarDados.setText("Alterar Dados");

        adicionarJog.setText("Adicionar Jogador");
        adicionarJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarJogActionPerformed(evt);
            }
        });
        alterarDados.add(adicionarJog);

        eliminarJog.setText("Eliminar Jogador");
        eliminarJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarJogActionPerformed(evt);
            }
        });
        alterarDados.add(eliminarJog);

        mudarIdade.setText("Mudar idade");
        mudarIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarIdadeActionPerformed(evt);
            }
        });
        alterarDados.add(mudarIdade);

        mudarNacion.setText("Mudar nacionalidade");
        mudarNacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarNacionActionPerformed(evt);
            }
        });
        alterarDados.add(mudarNacion);

        mudarClube.setText("Mudar clube atual");
        mudarClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarClubeActionPerformed(evt);
            }
        });
        alterarDados.add(mudarClube);

        mudarEstado.setText("Mudar estado");
        mudarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarEstadoActionPerformed(evt);
            }
        });
        alterarDados.add(mudarEstado);

        jMenuBar1.add(alterarDados);

        efetuarPesquisas.setText("Efetuar Pesquisas");

        pesquisarNome.setText("Nome Jogador");
        pesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarNomeActionPerformed(evt);
            }
        });
        efetuarPesquisas.add(pesquisarNome);

        pesquisarClube.setText("Por Clube");
        pesquisarClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarClubeActionPerformed(evt);
            }
        });
        efetuarPesquisas.add(pesquisarClube);

        pesquisarNacion.setText("Por Nacionalidade");
        pesquisarNacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarNacionActionPerformed(evt);
            }
        });
        efetuarPesquisas.add(pesquisarNacion);

        pesquisarPos.setText("Por Posição");
        pesquisarPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarPosActionPerformed(evt);
            }
        });
        efetuarPesquisas.add(pesquisarPos);

        pesquisarSituacao.setText("Por Situação");
        pesquisarSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarSituacaoActionPerformed(evt);
            }
        });
        efetuarPesquisas.add(pesquisarSituacao);

        pesquisarIntervaloIdade.setText("Por Intervalo de Idade");
        pesquisarIntervaloIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarIntervaloIdadeActionPerformed(evt);
            }
        });
        efetuarPesquisas.add(pesquisarIntervaloIdade);

        pesquisarSelecao.setText("Por Seleção");
        pesquisarSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarSelecaoActionPerformed(evt);
            }
        });
        efetuarPesquisas.add(pesquisarSelecao);

        jMenuBar1.add(efetuarPesquisas);

        gerarOutputs.setText("Gerar Outputs");

        HMTL_fotos.setText("Ficheiro HTML com fotos dos jogadores");
        gerarOutputs.add(HMTL_fotos);

        XML_clube.setText("Ficheiro XML com lista de jogadores de um clube");
        XML_clube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XML_clubeActionPerformed(evt);
            }
        });
        gerarOutputs.add(XML_clube);

        TXT_nacionalidade.setText("Ficheiro TXT com nomes de jogadores de uma nacionalidade");
        gerarOutputs.add(TXT_nacionalidade);

        XML_top.setText("Ficheiro XML com top 5 de jogadores mais valiosos");
        gerarOutputs.add(XML_top);

        jMenuItem5.setText("jMenuItem5");
        gerarOutputs.add(jMenuItem5);

        jMenuItem6.setText("jMenuItem6");
        gerarOutputs.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        gerarOutputs.add(jMenuItem7);

        jMenuBar1.add(gerarOutputs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geralActionPerformed

    private void validarDTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarDTDActionPerformed
        try {
            // TODO add your handling code here:
            int res = JDOMFunctions_Validar.validarDocumentoDTD("jogador.xml", "jogador.dtd");
            if (res == -1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro inválido por DTD",
                        "Informação Validação", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro válido por DTD",
                        "Informação Validação", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_validarDTDActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void mudarIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarIdadeActionPerformed
        newIdade.setSize(400, 250);
        newIdade.setLocation(200, 200);
        newIdade.setTitle("Alterar idade do jogador");
        newIdade.setVisible(true);
    }//GEN-LAST:event_mudarIdadeActionPerformed

    private void mudarClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarClubeActionPerformed
        newClube.setSize(400, 250);
        newClube.setLocation(200, 200);
        newClube.setTitle("Alterar clube do jogador");
        newClube.setVisible(true);
    }//GEN-LAST:event_mudarClubeActionPerformed

    private void pesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarNomeActionPerformed
        XPATH_nome.setSize(400, 250);
        XPATH_nome.setLocation(200, 200);
        XPATH_nome.setTitle("XPATH: pesquisar por nome");
        XPATH_nome.setVisible(true);
    }//GEN-LAST:event_pesquisarNomeActionPerformed

    private void pesquisarPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarPosActionPerformed
        XPATH_posicao.setSize(400, 250);
        XPATH_posicao.setLocation(200, 200);
        XPATH_posicao.setTitle("XPATH: pesquisar por posicao");
        XPATH_posicao.setVisible(true);
    }//GEN-LAST:event_pesquisarPosActionPerformed

    private void pesquisarIntervaloIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarIntervaloIdadeActionPerformed
        XPATH_intervaloIdade.setSize(400, 250);
        XPATH_intervaloIdade.setLocation(200, 200);
        XPATH_intervaloIdade.setTitle("XPATH: pesquisar por intervalo de idade");
        XPATH_intervaloIdade.setVisible(true);
    }//GEN-LAST:event_pesquisarIntervaloIdadeActionPerformed

    private void VerXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerXMLActionPerformed

        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("jogador.xml");
        if (doc == null) {
            output.setText("Ficheiro não existe");
        } else {
            String t = XMLJDomFunctions.escreverDocumentoString(doc);

            output.setText(t);
        }

    }//GEN-LAST:event_VerXMLActionPerformed

    private void adicionarJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarJogActionPerformed
        addJogador.setSize(400, 250);
        addJogador.setLocation(200, 200);
        addJogador.setTitle("Adicionar jogador");
        addJogador.setVisible(true);
    }//GEN-LAST:event_adicionarJogActionPerformed

    private void eliminarJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarJogActionPerformed
        remJogador.setSize(400, 250);
        remJogador.setLocation(200, 200);
        remJogador.setTitle("Remover jogador");
        remJogador.setVisible(true);
    }//GEN-LAST:event_eliminarJogActionPerformed

    private void addJogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJogButtonActionPerformed
        try {

            Jogador x = Wrappers.novoJogador(jTextField9.getText());

            Document doc = XMLJDomFunctions.lerDocumentoXML("jogador.xml");
            doc = ModeloXML.adicionaJogador(x, doc);
            addJogador.setVisible(false);

            if (doc != null) {
                XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "jogador.xml");
                JOptionPane.showMessageDialog(this,
                        "Jogador adicionado com sucesso",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Jogador já existe",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addJogButtonActionPerformed

    private void remJogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remJogButtonActionPerformed

        Document doc = XMLJDomFunctions.lerDocumentoXML("jogador.xml");
        String x = jTextField10.getText();
        doc = ModeloXML.removeJogadorNome(x, doc);
        remJogador.setVisible(false);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "jogador.xml");

            JOptionPane.showMessageDialog(this,
                    "Jogador removido com sucesso",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Jogador não existe",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_remJogButtonActionPerformed

    private void nIdadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nIdadeButtonActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("jogador.xml");

        String nome = jTextField1.getText();
        //System.out.println(nome);
        int idade = Integer.parseInt(jTextField2.getText());
        //System.out.println(estado);

        doc = ModeloXML.alteraIdade(nome, idade, doc);
        newIdade.setVisible(false);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "jogador.xml");

            JOptionPane.showMessageDialog(this,
                    "Idade alterada com sucesso",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Jogador não existe",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nIdadeButtonActionPerformed

    private void nNacionalidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nNacionalidadeButtonActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("jogador.xml");

        String nome = jTextField7.getText();
        //System.out.println(nome);
        String nacionalidade = (jTextField8.getText());
        //System.out.println(estado);

        doc = ModeloXML.alteraNacionalidade(nome, nacionalidade, doc);
        newNacionalidade.setVisible(false);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "jogador.xml");

            JOptionPane.showMessageDialog(this,
                    "Nacionalidade alterada com sucesso",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Jogador não existe",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nNacionalidadeButtonActionPerformed

    private void nClubeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nClubeButtonActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("jogador.xml");

        String nome = jTextField3.getText();
        //System.out.println(nome);
        String clube = (jTextField4.getText());
        //System.out.println(estado);

        doc = ModeloXML.alteraClubeAtual(nome, clube, doc);
        newClube.setVisible(false);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "jogador.xml");

            JOptionPane.showMessageDialog(this,
                    "Clube alterado com sucesso",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Jogador não existe",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nClubeButtonActionPerformed

    private void nEstadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nEstadoButtonActionPerformed

        Document doc = XMLJDomFunctions.lerDocumentoXML("jogador.xml");

        String nome = jTextField1.getText();
        //System.out.println(nome);
        String estado = (jTextField2.getText());
        //System.out.println(estado);

        doc = ModeloXML.alteraEstado(nome, estado, doc);
        newEstado.setVisible(false);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "jogador.xml");

            JOptionPane.showMessageDialog(this,
                    "Estado alterado com sucesso",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Jogador não existe",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nEstadoButtonActionPerformed

    private void mudarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarEstadoActionPerformed

        newEstado.setSize(400, 250);
        newEstado.setLocation(200, 200);
        newEstado.setTitle("Alterar estado do jogador");
        newEstado.setVisible(true);
    }//GEN-LAST:event_mudarEstadoActionPerformed

    private void mudarNacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarNacionActionPerformed
        newNacionalidade.setSize(400, 250);
        newNacionalidade.setLocation(200, 200);
        newNacionalidade.setTitle("Alterar nacionalidade do jogador");
        newNacionalidade.setVisible(true);
    }//GEN-LAST:event_mudarNacionActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void validarXSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarXSDActionPerformed
        try {
            // TODO add your handling code here:
            int res = JDOMFunctions_Validar.validarDocumentoXSD("jogador.xml", "jogador.xsd");
            if (res == -1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro inválido por XSD",
                        "Informação Validação", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro válido por XSD",
                        "Informação Validação", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_validarXSDActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String xp = "//jogador[@nome ='" + jTextField11.getText() + "']//text()";

            XdmValue res = XPathFunctions.executaXpath(xp, "jogador.xml");
            String s = XPathFunctions.listaResultadoNome(res);

            XPATH_nome.setVisible(false);

            if (res == null) {
                output.setText("Ficheiro XML não existe");
            } else if (res.size() == 0) {
                output.setText("Sem resultados");
            } else {

                output.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            String xp = "//jogador[contains(clubeAtual,'" + jTextField12.getText() + "')]//@nome";
            System.out.println(xp);

            XdmValue res = XPathFunctions.executaXpath(xp, "jogador.xml");
            String s = XPathFunctions.listaResultado(res);
            //ArrayList<String> clubes = new ArrayList();

            XPATH_clube.setVisible(false);
            if (res == null) {
                output.setText("Ficheiro XML não existe");
            } else if (res.size() == 0) {
                output.setText("Sem resultados");
            } else {
                //clubes.add(s);
                output.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String xp = "//jogador[contains(nacionalidade,'" + jTextField13.getText() + "')]//@nome";
            System.out.println(xp);

            XdmValue res = XPathFunctions.executaXpath(xp, "jogador.xml");
            String s = XPathFunctions.listaResultado(res);

            XPATH_nacionalidade.setVisible(false);
            if (res == null) {
                output.setText("Ficheiro XML não existe");
            } else if (res.size() == 0) {
                output.setText("Sem resultados");
            } else {
                //clubes.add(s);
                output.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String xp = "//jogador[contains(posicao,'" + jTextField14.getText() + "')]//@nome";
            System.out.println(xp);

            XdmValue res = XPathFunctions.executaXpath(xp, "jogador.xml");
            String s = XPathFunctions.listaResultado(res);
            //ArrayList<String> clubes = new ArrayList();

            XPATH_posicao.setVisible(false);
            if (res == null) {
                output.setText("Ficheiro XML não existe");
            } else if (res.size() == 0) {
                output.setText("Sem resultados");
            } else {
                //clubes.add(s);
                output.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            String xp = "//jogador[contains(selecao,'" + jTextField16.getText() + "')]//@nome";
            System.out.println(xp);

            XdmValue res = XPathFunctions.executaXpath(xp, "jogador.xml");
            String s = XPathFunctions.listaResultado(res);
            //ArrayList<String> clubes = new ArrayList();

            XPATH_selecao.setVisible(false);
            if (res == null) {
                output.setText("Ficheiro XML não existe");
            } else if (res.size() == 0) {
                output.setText("Sem resultados");
            } else {
                //clubes.add(s);
                output.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            String xp = "//jogador[(idade >= " + jTextField17.getText() + " and  idade <= " + jTextField18.getText() + ")]//@nome";
            System.out.println(xp);

            XdmValue res = XPathFunctions.executaXpath(xp, "jogador.xml");
            String s = XPathFunctions.listaResultado(res);
            //ArrayList<String> clubes = new ArrayList();

            XPATH_intervaloIdade.setVisible(false);
            if (res == null) {
                output.setText("Ficheiro XML não existe");
            } else if (res.size() == 0) {
                output.setText("Sem resultados");
            } else {
                //clubes.add(s);
                output.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void pesquisarClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarClubeActionPerformed
        XPATH_clube.setSize(400, 250);
        XPATH_clube.setLocation(200, 200);
        XPATH_clube.setTitle("XPATH: pesquisar por clube");
        XPATH_clube.setVisible(true);

    }//GEN-LAST:event_pesquisarClubeActionPerformed

    private void pesquisarNacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarNacionActionPerformed
        XPATH_nacionalidade.setSize(400, 250);
        XPATH_nacionalidade.setLocation(200, 200);
        XPATH_nacionalidade.setTitle("XPATH: pesquisar por nacionalidade");
        XPATH_nacionalidade.setVisible(true);
    }//GEN-LAST:event_pesquisarNacionActionPerformed

    private void pesquisarSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarSituacaoActionPerformed
        try {

            String xp = "//jogador[not(contains(estadoAtual,'No ativo'))]//@nome";
            //System.out.println(xp);

            XdmValue res = XPathFunctions.executaXpath(xp, "jogador.xml");
            String s = XPathFunctions.listaResultado(res);
            //ArrayList<String> clubes = new ArrayList();

            if (res == null) {
                output.setText("Ficheiro XML não existe");
            } else if (res.size() == 0) {
                output.setText("Sem resultados");
            } else {
                //clubes.add(s);
                output.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pesquisarSituacaoActionPerformed

    private void pesquisarSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarSelecaoActionPerformed
        XPATH_selecao.setSize(400, 250);
        XPATH_selecao.setLocation(200, 200);
        XPATH_selecao.setTitle("XPATH: pesquisar por selecao");
        XPATH_selecao.setVisible(true);
    }//GEN-LAST:event_pesquisarSelecaoActionPerformed

    private void XML_clubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XML_clubeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XML_clubeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem HMTL_fotos;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem TXT_nacionalidade;
    private javax.swing.JMenuItem VerXML;
    private javax.swing.JMenuItem XML_clube;
    private javax.swing.JMenuItem XML_top;
    private javax.swing.JDialog XPATH_clube;
    private javax.swing.JDialog XPATH_intervaloIdade;
    private javax.swing.JDialog XPATH_nacionalidade;
    private javax.swing.JDialog XPATH_nome;
    private javax.swing.JDialog XPATH_posicao;
    private javax.swing.JDialog XPATH_selecao;
    private javax.swing.JButton addJogButton;
    private javax.swing.JDialog addJogador;
    private javax.swing.JMenuItem adicionarJog;
    private javax.swing.JMenu alterarDados;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JMenu efetuarPesquisas;
    private javax.swing.JMenuItem eliminarJog;
    private javax.swing.JMenu geral;
    private javax.swing.JMenu gerarOutputs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem mudarClube;
    private javax.swing.JMenuItem mudarEstado;
    private javax.swing.JMenuItem mudarIdade;
    private javax.swing.JMenuItem mudarNacion;
    private javax.swing.JButton nClubeButton;
    private javax.swing.JButton nEstadoButton;
    private javax.swing.JButton nIdadeButton;
    private javax.swing.JButton nNacionalidadeButton;
    private javax.swing.JDialog newClube;
    private javax.swing.JDialog newEstado;
    private javax.swing.JDialog newIdade;
    private javax.swing.JDialog newNacionalidade;
    private javax.swing.JTextArea output;
    private javax.swing.JMenuItem pesquisarClube;
    private javax.swing.JMenuItem pesquisarIntervaloIdade;
    private javax.swing.JMenuItem pesquisarNacion;
    private javax.swing.JMenuItem pesquisarNome;
    private javax.swing.JMenuItem pesquisarPos;
    private javax.swing.JMenuItem pesquisarSelecao;
    private javax.swing.JMenuItem pesquisarSituacao;
    private javax.swing.JButton remJogButton;
    private javax.swing.JDialog remJogador;
    private javax.swing.JMenuItem validarDTD;
    private javax.swing.JMenuItem validarXSD;
    // End of variables declaration//GEN-END:variables
}
